spring:
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: dev
    include:
      - sdk

oneboot:
  common:
    snowflake:
      worker-id: 1
      datacenter-id: 1
