server:
  port: 8080
debug: true
spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: 123456
#logging:
#  level:
