server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    root: info
    com.github.alphafoxz.oneboot.common: error
    com.github.alphafoxz.oneboot.preset_sys: warn
    com.github.alphafoxz.oneboot.app: info
    org.springframework.web.servlet: debug