spring:
  aop:
    proxy-target-class: true
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: dev
    include:
      - dev-common
      - dev-preset_sys
      - dev-app
      - dev-sdk
