server:
  port: 8080
debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      pool-name: "MainHikariCP"
      connection-test-query: 'select 1'
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    root: info
    com.github.alphafoxz.oneboot.core: warn
    com.github.alphafoxz.oneboot.preset_sys: warn
    com.github.alphafoxz.oneboot.app: info
    com.github.alphafoxz.oneboot.sdk: debug
    org.springframework.web.servlet: debug

oneboot:
  core:
    base-package: com.github.alphafoxz.oneboot
    snowflake:
      worker-id: 1
      datacenter-id: 1
  starter:
    cache:
      cache-expire-ms: 1_800_000
      cache-max-size: 10_000
      cache-strategy: caffeine
    meilisearch:
      url: "http://127.0.0.1:7700"
      master-key: "123QWEasdzxcfffff"