server:
  port: 8080
debug: true
spring:
  datasource:
#    url: jdbc:h2:mem:test_db
    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.h2.Driver
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      pool-name: "MainHikariCP"
      connection-test-query: 'select 1'
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
#    jpa:
#      database: h2
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-admin-password: 123456
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    root: info
    com.github.alphafoxz.oneboot.common: warn
    com.github.alphafoxz.oneboot.preset_sys: warn
    com.github.alphafoxz.oneboot.app: info
    com.github.alphafoxz.oneboot.sdk: debug
    org.springframework.web.servlet: debug