oneboot:
  sdk:

dsl:
  restl:
    base-package: com.github.alphafoxz.oneboot
    include-modules:
      - preset_sys
      - app
      - sdk
    http-controller-class: com.github.alphafoxz.oneboot.core.standard.service.HttpController
    page-class: com.github.alphafoxz.oneboot.preset_sys.service.framework.Page
    gen-dto-fields:
      enabled: true
      package-name: _compile_only
