spring:
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: dev
    include:
      - dev-core
      - dev-preset_sys
      - dev-app
      - dev-sdk
      - dev-meilisearch_starter
