oneboot:
  sdk:

dsl:
  restl:
    base-package: com.github.alphafoxz.oneboot
    include-modules:
      - preset_sys
      - app
      - sdk
    http-controller-class: com.github.alphafoxz.oneboot.core.standard.framework.HttpController
    page-class: com.github.alphafoxz.oneboot.preset_sys.service.framework.Page
